name: intl_mobile_field
description: "A customized Flutter TextFormField to input international Mobile number along with country code."
version: 2.0.0
homepage: https://github.com/MdAshrafUllah/intl_mobile_field.git
issue_tracker: https://github.com/MdAshrafUllah/intl_mobile_field/issues
topics: [mobile-field, phone-field, number-field]

screenshots:
  - description: "intl_mobile_field"
    path: output/intl_mobile_field.png

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.17.12

flutter:
  uses-material-design: true
  assets:
    - assets/flags/
